/* Read-only, independently evaluated results; no truth enters diagnosis. */
function evaluatedValidation(){
 const r=validationReport,m=r.metrics.overall,q=r.data_quality;
 const number=value=>value===null?'未定义':value.toFixed(3);
 const qualityNames={missing_required_value:'必填值缺失',duplicate_point_key:'重复点键',invalid_coordinate:'无效坐标',time_anomaly:'时间异常',unsupported_speed:'异常速度'};
 const rates=q.record_rates.map(row=>`<tr><td>${qualityNames[row.metric]}</td><td>${pct(row.rate)}</td><td>${row.count} / ${row.denominator}</td></tr>`).join('');
 const checks=r.reproducibility;
 return hero('Validation Center / 结果验证中心','基于独立注入答案核对检测结果，展示漏检、数据质量与重复运行记录。',true)+
 `<div class="metrics six">${metric('Trajectory Points',count(q.input_points),'file','轨迹点数')}${metric('Accepted Records',count(q.accepted_points),'check','通过记录清洗','green')}${metric('Map Matching Rate',pct(q.matching_success_rate),'link','规则接受率')}${metric('Avg Match Distance',q.mean_matched_distance_m===null?'—':q.mean_matched_distance_m.toFixed(2)+' m','pin','平均匹配距离')}${metric('Precision',number(m.precision),'chart','合成基准 · 非现实准确率')}${metric('Recall',number(m.recall),'refresh',`命中 ${m.tp} / ${m.injected}`)}</div>`+
 (q.matching_status==='warning'?'<div class="alert-note error-note">匹配成功率低于 '+pct(q.matching_warning_threshold)+'，当前数据质量不足，请核对输入与匹配结果。</div>':'')+
 `<div class="validation-grid top-row">${card('Data Quality / 数据质量','file',`<table class="data-table"><thead><tr><th style="width:35%">指标</th><th style="width:22%">数值</th><th>记录数 / 口径</th></tr></thead><tbody>${rates}<tr><td>匹配接受率</td><td>${pct(q.matching_success_rate)}</td><td>告警线 ${pct(q.matching_warning_threshold)}</td></tr><tr><td>P95 匹配距离</td><td>${q.p95_matched_distance_m===null?'—':q.p95_matched_distance_m.toFixed(2)+' m'}</td><td>非真实定位误差</td></tr><tr><td>低评分候选</td><td>${pct(q.low_confidence_rate)}</td><td>${q.low_confidence_count} 个 · &lt; ${pct(q.low_confidence_threshold)}</td></tr></tbody></table><p class="note">异常原因可重叠；拒绝记录保留审计。</p>`)}
 ${card('Benchmark Result / 基准验证','chart',`<div class="benchmark-counts">${[['注入故障',m.injected],['检测候选',m.detected],['匹配 TP',m.tp],['未匹配 FP',m.fp]].map(([name,value])=>`<div><small>${name}</small><strong>${value}</strong></div>`).join('')}</div><div class="evaluation-bars">${[['Precision',m.precision,'#4195ff'],['Recall',m.recall,'#11bd91'],['F1',m.f1,'#9c78ff']].map(([name,value,color])=>`<div><strong>${number(value)}</strong><div class="evaluation-bar-track"><i style="height:${value===null?0:value*100}%;background:${color}"></i></div><small>${name}</small></div>`).join('')}</div><p class="note">Seed ${r.source.seed} · 一对一对象匹配 · 漏检 ${m.fn} 个</p>${link('查看 TP / FP / FN 明细','evaluation-details')}`)}
 ${card('Run Metadata / 运行元数据','settings',`<div class="metadata-table">${kv('数据集',esc(data.dataset_label))}${kv('网络版本',`<span title="${esc(r.source.network_version)}">${esc(r.source.network_version)}</span>`)}${kv('评估算法',esc(r.algorithm_version))}${kv('评估运行 ID',`<span title="${esc(r.run_id)}">${esc(r.run_id)}</span>`)}${kv('运行时间',fmtDate(r.started_at))}${kv('规则版本',esc(r.rules_version.slice(0,16)))}${kv('随机种子',String(r.source.seed))}</div><p class="note" style="margin-top:10px">缺路匹配：${r.rules.missing_buffer_m} m 缓冲；故障覆盖 ≥ ${pct(r.rules.minimum_fault_coverage)}、候选覆盖 ≥ ${pct(r.rules.minimum_candidate_coverage)}。</p>${link('完整参数、耗时与来源','evaluation-details')}`)}</div>`+
 `<div class="validation-grid bottom-row">${card('Fault Injection Cases / 故障注入案例','alert',`<table class="data-table"><thead><tr><th style="width:39%">问题类型</th><th>注入</th><th>TP</th><th>FN</th><th>Recall</th></tr></thead><tbody>${Object.keys(TYPES).map(key=>{const v=r.metrics.by_type[key];return `<tr><td>${TYPES[key].zh}</td><td>${v.injected}</td><td>${v.tp}</td><td class="${v.fn?'orange':''}">${v.fn}</td><td>${pct(v.recall)}</td></tr>`;}).join('')}</tbody></table><p class="note">每类至少 3 个故障；类型与对象同时匹配。</p>`)}
 ${card('Detection Outcomes / 检测结果汇总','layers',`<div class="outcome-grid">${[['匹配告警 TP',m.tp],['未匹配告警 FP',m.fp],['未命中故障 FN',m.fn],['正常对象 TN','未定义']].map(([title,value])=>`<div><small>${title}</small><strong>${value}</strong></div>`).join('')}</div><p class="note" style="margin-top:10px">故障和候选一对一计数。没有完整负例全集，TN / FPR 未定义，不作为完整二分类矩阵。</p>`)}
 ${card('Run History / 运行历史','clock',`<table class="data-table"><thead><tr><th style="width:45%">运行时间</th><th>任务</th><th>状态</th></tr></thead><tbody>${[[data.analysis_run.started_at,'问题诊断'],[data.replay_run.started_at,'路线重放'],[r.started_at,'基准评估']].map(([date,name])=>`<tr><td>${fmtDate(date)}</td><td>${name}</td><td><span class="badge ok">完成</span></td></tr>`).join('')}</tbody></table><div class="alert-note ${checks.status==='passed'?'success-note':''}">${checks.status==='passed'?'两次完整重跑结果一致':'尚未执行完整重复性检查'}</div>${link('查看重复性与性能记录','evaluation-details')}`)}</div>`+
 flow(true)+'<p class="footer-note">当前为合成、非盲测 Benchmark；指标仅针对当前注入故障，不代表真实道路准确率。修复仍是未经现场核验的假设。</p>';
}
